In [191]:
import os
import pandas as pd
import re

In [286]:
current_dir = os.path.dirname(os.path.abspath("__file__"))

In [227]:
resume_csv_path = os.path.join(current_dir, "..", "Resume-Dataset", "Resume", "Resume.csv")

resume = pd.read_csv(resume_csv_path)

In [228]:
resume.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [229]:
resume.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   object
 2   Resume_html  2484 non-null   object
 3   Category     2484 non-null   object
dtypes: int64(1), object(3)
memory usage: 77.8+ KB

In [230]:
resume[["Category"]].describe()

                      Category
count                     2484
unique                      24
top     INFORMATION-TECHNOLOGY
freq                       120

In [231]:
resume['Category'].unique()

array(['HR', 'DESIGNER', 'INFORMATION-TECHNOLOGY', 'TEACHER', 'ADVOCATE',
       'BUSINESS-DEVELOPMENT', 'HEALTHCARE', 'FITNESS', 'AGRICULTURE',
       'BPO', 'SALES', 'CONSULTANT', 'DIGITAL-MEDIA', 'AUTOMOBILE',
       'CHEF', 'FINANCE', 'APPAREL', 'ENGINEERING', 'ACCOUNTANT',
       'CONSTRUCTION', 'PUBLIC-RELATIONS', 'BANKING', 'ARTS', 'AVIATION'],
      dtype=object)

In [232]:
resume['Category'].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
FINANCE                   118
ADVOCATE                  118
ACCOUNTANT                118
ENGINEERING               118
CHEF                      118
AVIATION                  117
FITNESS                   117
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [ ]:
def extract_job_title(resume_str):

    match = re.match(r"^[A-Z0-9(),.&/'\s-]+(?:[A-Z0-9(),.&/']{2,})", resume_str.strip())
    if match:
        return match.group(0).split("\n")[0].strip() 
    return None  

resume["job_title"] = resume["Resume_str"].apply(extract_job_title)

if resume["job_title"].isnull().any():
    print("Warning: Some resumes do not have a job title in uppercase at the beginning.")

Warning: Some resumes do not have a job title in uppercase at the beginning.

In [234]:
resume['job_title'].value_counts()

job_title
CONSULTANT                           83
ACCOUNTANT                           58
TEACHER                              51
SALES ASSOCIATE                      43
SALES                                28
                                     ..
ADULT EDUCATION INSTRUCTOR            1
PROJECT ASSISTANT                     1
E-COMMERCE SUPERVISOR                 1
PROGRAM SUPPORT ASSISTANT             1
PROGRAM DIRECTOR / OFFICE MANAGER     1
Name: count, Length: 1584, dtype: int64

In [235]:
resume=resume.drop(columns=['Resume_html'])

In [236]:
resume.head()

,ID,Resume_str,Category,job_title
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,HR ADMINISTRATOR/MARKETING ASSOCIATE
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...",HR,"HR SPECIALIST, US HR OPERATIONS"
2,33176873,HR DIRECTOR Summary Over 2...,HR,HR DIRECTOR
3,27018550,HR SPECIALIST Summary Dedica...,HR,HR SPECIALIST
4,17812897,HR MANAGER Skill Highlights ...,HR,HR MANAGER

In [237]:
resume.columns

Index(['ID', 'Resume_str', 'Category', 'job_title'], dtype='object')

In [238]:
resume.isnull().value_counts()

ID     Resume_str  Category  job_title
False  False       False     False        2457
                             True           27
Name: count, dtype: int64

In [239]:
null_rows=resume[resume.isnull().any(axis=1)]
null_rows

,ID,Resume_str,Category,job_title
61,20925036,Summary Chicago\nHR generalist offeri...,HR,None
193,30965258,Zachory Edmiston Summary...,DESIGNER,None
222,91635250,Christopher Townes Summa...,INFORMATION-TECHNOLOGY,None
249,12635195,Objective To obtain a position in the i...,INFORMATION-TECHNOLOGY,None
416,28933005,Kimberly Fisheli Summary Ded...,TEACHER,None
419,45987048,Marilyn Hunter Summary Focus...,TEACHER,None
420,99244405,Kpandipou Koffi Summary ...,TEACHER,None
474,10344379,Summary Administrative support professi...,ADVOCATE,None
656,12632728,,BUSINESS-DEVELOPMENT,None
691,37374340,Rachael Lobdell Summary . ...,HEALTHCARE,None
1080,14358578,Camryn Hilliard Professional S...,SALES,None
1157,17025292,Qualifications Microsoft Office...,CONSULTANT,None
1218,21156767,Pavithra Shetty Summary ...,CONSULTANT,None
1348,22946204,Highlights Prog. Languages: ...,AUTOMOBILE,None
1361,30311202,RM Roxanne Mejia Summary ...,CHEF,None
1426,16248476,"Summary Sous Chef, Lead Cook and Superv...",CHEF,None
1431,29775391,EXÉCUTIVE BANQUETTE SOUS CHEF P...,CHEF,None
1447,19268120,Summary I am a kitchen manager with s...,CHEF,None
1452,18036030,Ashanique Gray Summary ...,CHEF,None
1633,99806115,Rachel Guardado Summary ...,APPAREL,None
1830,21338490,Summary I have many years of experie...,ACCOUNTANT,None
1948,12491898,Work History Company Name ...,CONSTRUCTION,None
2049,24559558,D R Daiana Rocha Summa...,PUBLIC-RELATIONS,None
2175,28419927,Karla Lee Summary Results-fo...,BANKING,None
2228,65864767,VP Career Focus To lead the ...,BANKING,None
2230,26673507,Professional Summary Knowledgeable of ...,BANKING,None
2327,37751611,"Professional Summary Detail-oriented,...",ARTS,None

In [240]:
resume=resume.dropna()
resume.head()

,ID,Resume_str,Category,job_title
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,HR ADMINISTRATOR/MARKETING ASSOCIATE
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...",HR,"HR SPECIALIST, US HR OPERATIONS"
2,33176873,HR DIRECTOR Summary Over 2...,HR,HR DIRECTOR
3,27018550,HR SPECIALIST Summary Dedica...,HR,HR SPECIALIST
4,17812897,HR MANAGER Skill Highlights ...,HR,HR MANAGER

In [241]:
resume.isnull().value_counts()

ID     Resume_str  Category  job_title
False  False       False     False        2457
Name: count, dtype: int64

In [258]:
resume.to_csv(resume_csv_path,index=False)

In [280]:
job_csv_path = os.path.join(current_dir, "..", "Resume-Dataset", "training_data.csv")

job_desc = pd.read_csv(job_csv_path)

In [273]:
job_desc.head()

,company_name,job_description,position_title,description_length,model_response
0,Google,minimum qualifications\nbachelors degree or eq...,Sales Specialist,2727,"{\n ""Core Responsibilities"": ""Responsible fo..."
1,Apple,description\nas an asc you will be highly infl...,Apple Solutions Consultant,828,"{\n ""Core Responsibilities"": ""as an asc you ..."
2,Netflix,its an amazing time to be joining netflix as w...,Licensing Coordinator - Consumer Products,3205,"{\n ""Core Responsibilities"": ""Help drive bus..."
3,Robert Half,description\n\nweb designers looking to expand...,Web Designer,2489,"{\n ""Core Responsibilities"": ""Designing webs..."
4,TrackFive,at trackfive weve got big goals were on a miss...,Web Developer,3167,"{\n ""Core Responsibilities"": ""Build and layo..."

In [274]:
job_desc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company_name        853 non-null    object
 1   job_description     853 non-null    object
 2   position_title      853 non-null    object
 3   description_length  853 non-null    int64
 4   model_response      853 non-null    object
dtypes: int64(1), object(4)
memory usage: 33.4+ KB

In [281]:
job_desc=job_desc.drop(columns=['company_name','description_length','model_response'])

In [282]:
job_desc.columns

Index(['job_description', 'position_title'], dtype='object')

In [265]:
job_desc['position_title'].describe()

count                 853
unique                725
top       Sales Associate
freq                    9
Name: position_title, dtype: object

In [266]:
job_desc['position_title'].unique()

array(['Sales Specialist', 'Apple Solutions Consultant',
       'Licensing Coordinator - Consumer Products', 'Web Designer',
       'Web Developer', 'Frontend Web Developer',
       'Remote Website Designer', 'SR. Web Designer',
       'Senior UI Designer', 'Wordpress Web Developer', 'UI Web Designer',
       'Senior Web Designer (REMOTE)', 'Chief Executive Officer',
       'Executive Vice President & Chief Executive Officer (CEO), Medical...',
       'CEO', 'CEO, Positivly',
       'Chief Executive Officer - CEO Consultant',
       'Chief Executive Officer - Healthcare - Columbus', 'CEO Coach',
       'Assistant Vice President Premier Relationship Manager',
       'Digital Marketing Specialist', 'Senior Marketing Specialist',
       'Performance Marketing Specialist, Paid Media',
       'Software Engineer - Reno, NV', 'Software Engineer',
       'Entry Level Software Engineer', 'Associate Software Engineering',
       'Software Engineer (JavaScript Backend)',
       'Senior Software Engineer', 'Warehouse Manager',
       'Warehouse Manager IV', 'Warehouse Supervisor',
       'Warehouse Management Specialist',
       'Warehouse Manager - Lexington, KY', 'Bank Teller',
       'Part-time Bank Teller/Financial Services Representative',
       'Full Time Teller', 'Seasonal Teller', 'Sales Executive',
       'Sales Executive III Client Management', 'Sales Manager',
       'Account Executive',
       'Account Executive - Columbus, OH - AMO Sales and Services, Inc..',
       'Workday Sales Director', 'Account Executive (Inside Sales)',
       'Business Sales Account Executive', 'Full Stack Web Developer',
       'Web Developer (Front-End)', 'Front-End Engineer/UI Developer',
       'Software Engineer (Web)',
       'Interns (Web Developers Mobile Developers Game Developers)',
       'Supply Chain Analyst', 'Supply Chain Analyst IV',
       'Supply Chain Analyst (ED)',
       'Analyst II, Supply Chain - Corporate - US (Open)',
       'Supply Chain Analyst - Senior', 'Business Analyst- Supply Chain',
       "Commission Sales Associate - Men's, Full Time - Beverly Center",
       'Commission Sales Associate',
       'Retail Commission Sales Associate - Fine Jewelry, Del Amo Fashion...',
       'Retail Commission Sales Associate - Fine Jewelry, Northridge...',
       'Kitchen prep / cleaning', 'Kitchen Cleaner',
       'Kitchen Cleaner (Utility)', 'Dishwasher/Kitchen Cleaner',
       'Utility Cleaner - Kitchen ($19.77/hr)',
       'Overnight Janitor - Los Angeles, California', 'Dishwasher',
       'Kitchen Exhaust Associate (Commerce, CA)',
       'Senior Software Developer - Up to 160k - 100% Remote',
       'Software Developer - New Graduate',
       'Software Engineer (US-Remote)', 'Software Developer',
       'Senior Software Developer- Full Stack (Remote)',
       'Full Stack Software Engineer', 'Software Engineer (Remote)',
       'Vice President Operations',
       'Bank President Jobs in Columbus, Ohio',
       'Senior Vice President of Property Management',
       'Regional Vice President of Sales',
       'Health Solutions, Vice President Actuary',
       'Vice President for Inclusive Excellence', 'Marketing Director',
       'Director, Audience Marketing', 'Director, Sales & Marketing',
       'B2B Marketing Manager', 'SAP Alliance Marketing Director',
       'Marketing Director – E-Learning – Columbus, OH',
       'Enterprise Sales Executive',
       'Multi-Media Advertising Sales Executive',
       'Field Sales Representative- Columbus, Ohio',
       'Outside Sales Executive, Remote', 'Retail Sales Associate',
       'Sales Associate - Easton T/C', 'Part-Time Sales Associate',
       'Selling - Inside Sales Associate',
       'PT-Sales Associate - ProServices-Flexible',
       'Retail Sales Associate - Full Time or Part Time (Columbus, Ohio)',
       'Sales Associate - Sun Center',
       'Business Development Center Representative - Performance Columbus',
       'Business Development Sales Representative - Columbus',
       'Business Development Center Representative - Performance Cadillac GMC',
       'Business Development Representative',
       'Automotive Business Development Center (BDC) Representative',
       'Registered Nurse', 'Bilingual Occupational Registered Nurse',
       'Registered Nurse (RN)', 'Registered Nurse (RN-CA02-007)',
       'Registered Nurse Casual Mount Royal', 'Senior Manager, Test',
       'Testing Monitor (DGE) - Part Time (NYC)',
       'Firmware Test Engineer', 'Test Center Monitor',
       'Software Engineer, Test, Advertising',
       'Bulk Product Testing Coordinator', 'Salesforce.com QA Tester',
       'Test Developer', 'Program Compliance Manager',
       'Program Compliance Manager - Remote',
       'Governance, Risk & Compliance Program Manager',
       'Compliance Manager', 'Compliance Director',
       'Sr analyst compliance', 'Marketing Manager',
       'College and Career Advisor - Cuyahoga County', 'Job Coach',
       'Career Specialist Instructor',
       'Digital Marketing Sales - Own the Territory – Run the Show',
       'Advisory Strategic Resource Manager',
       'Water Resources Project Manager', 'Criminal Investigator 2',
       'Criminal Investigator', 'Public investigator',
       'Organized Retail Crime Investigator- Virtual- Columbus',
       'Private Investigator', 'Entry Level Surveillance Investigator',
       'Criminal justice', 'Surveillance Investigator',
       'Claims Investigator', 'Inventory Clerk', 'Inventory Coordinator',
       'Civil Rights Investigator 1 - Columbus',
       'Credit Collections Lead',
       'Staff Software Engineer - SMB - Marketing Enablement',
       'Patient Services Specialist (Remote)', 'Accounts Receivable-FC',
       'Collections',
       'Financial Professional – Financial / Insurance – Entry Level',
       'Insurance Agent', 'Entry-Level Sales',
       'Vice President/General Manager (VP/GM)',
       'Vice President/Practice Leader of Tax',
       'Senior Vice President and Managing Director, International Research',
       'Customer Service - Fraud Liaison Specialist',
       'Fraud Awareness Educator – Associate', 'Fraud Resolution Analyst',
       'Fraud Systems Analyst (REMOTE OPPORTUNITY)',
       'Fraud & Compliance - AML/BSA Specialist', 'Fraud Investigator',
       'Office Clerk', 'General Office Clerk', 'OPS DEPUTY CLERK',
       'Part-Time Office Services Clerk',
       'General Office Clerk / Data Entry', 'General Clerk II',
       'Runner (Mail Clerk)', 'Clerical',
       'Medicaid Fraud Intake Officer  (22000555)', 'Investigator 1G',
       'CDL Team Truck Driver and Lease Operators +',
       'CDL-A Flatbed Truck Driver', 'CDL A Regional Drivers',
       'Dump Truck Driver', 'CDL Local Route Delivery Truck Driver',
       'CDL-A Truck Driver - $5K Sign On Bonus',
       'CDL A Team Drivers - Sign-On Bonus Up To $10,000!',
       'Class A - Regional Truck Driver - Home Weekly - Out 2 Days or Less',
       'Solo Class A CDL Driver', 'CEO - Cannabis & Investment',
       'Chief of Staff', 'CFO - Fast Growing Startup',
       'Chief Executive Officer (CEO)', 'Chief Financial Officer (CFO)',
       'Allstate Agency Owner - CEO of You',
       'Customer Service Representative - Remote',
       'Customer Service Representative (Work at Home)', 'Investigator',
       'Diversion Investigator',
       'Polygraph Examiner - Entry to Mid-Level (MD)', 'Special Agent',
       'MARKETING SPECIALIST',
       'Marketing Specialist/ Brand Marketing || Work from Home',
       'Marketing Specialist', 'Marketing Event Coordinator',
       'Background Investigator (FT Employee) - Arlington, VA',
       'Polygraph Examiner', 'Construction Project Manager',
       'Project Manager (CCR focused)', 'Sr. Project Manager',
       'Infrastructure Services Project Manager',
       'Project Manager 100% Remote', 'Environmental Project Manager',
       'Project Manager', 'Digital Development Project Manager',
       'Ecommerce Manager  Remote', 'Senior eCommerce Engineer',
       'E-Commerce Manager', 'Remote E-Commerce Technical Analyst',
       'IT Project Manager III - Contract to Hire - Fortune Client',
       'Ecommerce Consultant',
       'Senior Project Manager - eCommerce-Certified Scrum Master',
       'Manager, Commerce Marketing', 'Project Manager I/II- Remote',
       'Ecommerce Account Manager', 'Manager ecommerce',
       'Remote Customer Service Representative',
       'Bilingual Spanish CUSTOMER SERVICE REPRESENTATIVE Work From Home...',
       'Customer Service Representative L2 (Work-At-Home)',
       'Customer Service Representative',
       'Customer Service Representative - (1st Shift) - Remote',
       'Customer Service Representative / Remote',
       'Part-Time Customer Service Representative (Remote)',
       'Remote Customer Service Associate',
       'Work From Home Customer Service Representative',
       'Talent Acquisition Specialist / Recruiter',
       'Talent acquisition recruiter',
       'Talent Acquisition Coordinator/ Technical Recruiter (100% Remote...',
       'Talent Acquisition Advisor (Healthcare)   REMOTE',
       'Talent Acquisition Specialist', 'Talent Acquisition Manager',
       'Senior Talent Acquisition Specialist', 'Recruiter',
       'Marketing Visionary', 'COORDINATOR - MARKETING',
       'Digital Marketing Specialist (REMOTE)',
       'Marketing Content Specialist (Remote)',
       'Full Time Digital Marketing Specialist - Columbus, OH',
       'Customer Service Representative ', 'Test position', 'Coach',
       'Fitness Coach',
       'Strength & Conditioning Coach Jobs at Onelife Fitness – Falls...',
       'Fraud Representative', 'HTML and Wordpress Developer',
       'Wordpress Developer', 'E-commerce Strategist', 'Data Entry Clerk',
       'Data Entry Specialist', 'Data Entry - Brecksville',
       'Attorney in Brooklyn, NY', 'Landlord Tenant Attorney',
       'Litigation - General/Commercial Attorney in Brooklyn, NY',
       'Program Director / Supervising Attorney', 'Enforcement Attorney',
       'Attorney, CAMBA Legal Services, Brooklyn', 'Staff Attorney',
       'Sales And Marketing Specialist',
       'US Sales & Marketing - Consumer Specialist - Executive Director',
       'Sales & Marketing Specialist',
       'Senior Sales Marketing Specialist (Programmatic)',
       'Sales and Marketing Coordinator', 'Growth Marketing Specialist',
       'Marketing Coordinator', 'Social Media Manager',
       'Email marketing specialist', 'Pharmacy Marketing Representative',
       'Career Coach (Remote)',
       'Career Coach Waitlist (Part-time/Contract/US Remote)',
       'Career Advisor (Career Coach)',
       'Career Coach, Alumni Talent Services',
       'Career Services Coach-Remote Full Time', 'Career Coach',
       'Career Coach (Remote Accepted)',
       'Technical Support Agent (Remote)',
       'Remote Technical Support Agent',
       'Technical Support Representative - Work from Home!',
       'Part-Time Technical Support Agent (Remote)',
       'Customer Support Agent (remote)',
       'Technical Support Agent (Remote CT/MT/PT USA)',
       'Tech Support Agent - Remote US', 'Clinical Educator Part Time',
       'Perioperative Educator',
       'Special Education Teacher 2022/2023 School Year',
       'Teachers at Alpha Park KinderCare',
       'K-12 Director of Educational Partnerships, Northeast - Remote #1931',
       'Remote Education Advocate',
       'Cardiology Clinical Educator - Cleveland',
       'Brand Educator - Cleveland, Ohio (Remote)',
       'Senior Project Manager', 'Remote Project Manager',
       'Project Manager/Ship Manager',
       'Remote - Release Project Manager - San Diego, CA or North Carolina',
       'Sales Associate', 'Sales Associate – Luxury Brand in NYC!',
       'Manager, Sales and Customer Service', 'Customer Service/Sales',
       'Sales And Marketing Representative', 'Sales Professional',
       'Sales Service Representative',
       'Sales Associate / Customer Service Representative',
       'Career Coach Counselor',
       'Remote Work from Home Part Time Data Entry - Entry Level',
       'Sales Associate (Providence, RI)',
       'Sales Representative / Sales Associate',
       'Sales Associates- Providence Place',
       'Sales Associate Totally Pagoda,Providence Place Mall',
       'Sales Associate- FT', 'Remote Software Developer (Remote)',
       'Software Engineer I ( 100% Remote)', 'Software Engineer (remote)',
       'Senior / Lead Software Engineer (Remote)',
       'Senior Software Engineer -  Virtualization Group - (Remote)',
       'Senior Full Stack Software Engineer- Remote',
       'Java Software Engineer - Mid Level (REMOTE)',
       'Biotech Equity Research Associate', 'Art Teacher',
       'Senior graphic designer', 'Remote RN Case Manager',
       'RN Case Manager- REMOTE', 'Case Manager I - Remote',
       'Remote Case Manager II', 'Case Manager, RN - Remote',
       'Associate New Business Case Manager - Remote',
       'DI Case Manager - 100% remote US',
       'Medical Case Manager - (Remote)',
       'Sales Associate-COLONY SQUARE MALL',
       'Part Time Sales - Zanesville, OH',
       'Part-Time Retail Sales Associate', 'coach',
       'Therapeutic Coach Team Lead',
       'Direct Support Professional/Job Coach',
       'Human Resources Director', 'Human Resources Manager',
       'Director human resources', 'Director, Human Resources',
       'Human Resource Coordinator', 'HR Director, Americas',
       'Human Resources Generalist',
       'Customer Channel Service Representative',
       'Construction Project Manager - Remote',
       '(3) Construction Project Managers (Remote) (industrial structures)',
       'Construction Project Manager (Remote)',
       'Project Manager, Construction Manager (Remote), Project ...',
       'REMOTE FLEX - Construction Project Manager',
       'Construction Project Manager- (Remote in Detroit, Cleveland, or...',
       'Real Estate Investment Management Associate (Monsey)',
       'Senior Financial Analyst',
       'Sr. Software Engineer, Networking (Remote)',
       'GRC Product Risk Analyst (Remote)', 'Windows Packaging Engineer',
       'Engineering Lead - Analytics Platform',
       'Holman Frenia Allison, PC Hiring for Audit Staff Accountant Job at...',
       'Accounting Clerk', 'Senior Accountant, Banking (Lakewood)',
       'Audit Staff Accountant', 'Assurance Senior, Public Accounting',
       'Accountant', 'Business Development Specialist',
       'Business Development Associate',
       'Business Development Manager - Talent and Technology Solutions',
       'Business Development & Sales Analyst II',
       'Business Development Manager (Monsey)',
       'Manager Business Development',
       'Business Development Manager Private Equity',
       'Sr Manager - Business Development',
       'Information Technology System Administrator',
       'Systems Administrator, IT (Brooklyn, NY)',
       'Network and Systems Administrator (On-Site ~ NOT REMOTE)',
       'Network and Systems Administrator', 'It Systems Administrator Ii',
       'Network Systems Admin', 'Systems Administrator',
       'Regional Sales Manager', 'Assistant Sales Manager - Full Time',
       'Service Manager',
       'Regional Sales Director, SAP - NE - United States',
       'Regional Sales Manager, Video Conferencing (East)',
       'Sales Leader I - Business Banking Sales Manager',
       'Regional Sales Manager - Air Solutions NE',
       'Licensed Insurance Agent Remote Executive Sales Manager',
       'Sales leader', 'Senior Director Finance', 'Director of Finance',
       'Financial Analyst', 'VP of Finance (East Meadow)',
       'Director - FP&A / Corporate Finance',
       'Director Financial Business Management (Freeport)',
       'Chief Financial Officer',
       'Associate Director, Global Capital Markets Documentation, GBM...',
       'Furniture Product Sales Liasion', 'Data Analyst/Manager',
       'Manager, Data Analytics', 'Data Analyst Manager',
       'Senior Data Analyst', 'Analytics Manager',
       'Marketing Analytics Manager',
       'Data Management Analyst for Netsmart',
       'Associate Project Manager, IVD Product Development (San Diego, CA)',
       'Sr. Product Marketing Manager - Growth, Music Industry',
       'Marketing Program Manager, B2B',
       'Systems Analyst - Appserver Admin',
       'Administrative Executive Assistant - Building Operations',
       'Office Administrator', 'Academic Dean, VOICE Charter School',
       'Assistant RN Manager Telemetry - Night shift',
       'Project Management Administrator', 'Nurse Administrator',
       'Administrative Assistant', 'Site Administrative Assistant',
       'Sr. HR Business Partner (Hybrid/Remote Role)',
       'Senior HR Business Partner', 'HR Generalist',
       'HR Initiatives Program Lead (Remote)',
       'Federal - Nursing Assistant Inpatient Mental Health West',
       'Nursing Assistant (Inpatient Mental Health)',
       'Sylmar Certified Nursing Assistant CNA for Psychiatric lockdown...',
       'Certified nursing assistant',
       'Nurse Practitioner - Icu Davies - Pd',
       'Mental Health Worker/CNA, Full Time, Nights',
       'Real Estate Agent - Training Provided',
       'Entry-Level Commercial Real Estate Agent', 'Realtor',
       'Real Estate Agent', 'VP Real Estate',
       'Creative Real Estate Agent in Nyc (We Train You)',
       'Coordinator, Customer Care Center',
       'Investment Service Partner – Customer Service Rep – REMOTE OPTION',
       'Customer Service Representative / Inside Sales',
       'Customer Care Embracer', 'Customer Support Specialist',
       'Editor (Remote or Onsite)', 'Director, Strategy & Operations',
       'Sr. Director/Head of Strategy and Business Operations',
       'Management Consulting Director- Strategy and Operations (San...',
       'Sr. Director of Strategy & External Relations',
       'Manager, Business Strategy And Operations',
       'Director / Sr Director, Strategic Operations Management (Product ...',
       'Staff Strategic Operations Manager',
       'Project Manager - Strategy & Operations Transformation Lead',
       'Vice President, Head of Global Medical Affairs',
       'PCA & ESA (Phase 1 & 2) Vice President',
       'Vice President/Sr. Director Business Development - CME',
       'VP, Healthcare Services',
       'Vice President of Operations - Indianapolis & St. Louis',
       'Senior Embedded C++ Developer', 'C++ Embedded Engineer',
       'Specialist, Embedded C++ Software Engineer',
       'Owner Operators Just Announced: Largest rate increase in Forward...',
       'Hosts / Hostesses', 'Astonishing Homecare Drivers',
       'C++ Embedded Engineer with Security Clearance',
       'Software Engineering', 'Banking Center Supervisor',
       'Application Development -L6', 'Commercial Construction Manager',
       'Corporate Recruiter (Remote)',
       'Technical Sourcing Recruiter (US Remote)', 'Corporate Recruiter',
       'Senior Tech Recruiter (Remote)', 'Full-Cycle Recruiter (Remote)',
       'Senior Corporate Recruiter (Contract) - (Remote - US)',
       'Data Analytics Senior Mangager', 'Marketing Intern',
       'Marketing Communications Intern - Fall 2023',
       'Marketing & Communications Intern',
       'Digital Marketing Internship at EdTech Start-up',
       'Sales Intern (CLE)', 'Advertising Design Intern - 2022',
       'Social Media and Marketing Intern', 'VP Client Development',
       'Senior Analyst, ECommerce, Search Marketing',
       'Fractional CEO - B2B - Remote', 'Executive Assistant to the CEO',
       'Executive Assistant to CEO',
       'Senior Strategy Lead, Office of the CEO', 'CEO/Co-Founder',
       'Executive Assistant to CEO at Chartis Federal (Hybrid: Remote ...',
       'The Judge Group  New York, NY', 'Sr. System Administrator',
       'Systems administrator', 'Business Development Executive',
       'Business Development Executive /Remote with Travel/ - with Growth...',

In [267]:
job_desc['position_title'].value_counts()

position_title
Sales Associate                                     9
Retail Sales Associate                              9
Project Manager                                     7
Inventory Clerk                                     6
Systems Administrator                               6
                                                   ..
Senior Sales Marketing Specialist (Programmatic)    1
Sales and Marketing Coordinator                     1
Growth Marketing Specialist                         1
Marketing Coordinator                               1
Remote Inbound Customer Service Representative      1
Name: count, Length: 725, dtype: int64

In [287]:
job_desc.to_csv(job_csv_path, index=False)